#File Updated
#Wed Jan 03 00:33:54 IST 2024
_id=659444634077517ceaa1793d
dateOfBirth=
email=abcde@gmail.com
mongodb.uri=mongodb+srv\://aadhavan\:A8UJrCKG2LmmCwm3@cluster0.7ibodeh.mongodb.net/asianex?w\=majority
name=
password=\uFFFD\uFFFD\uFFFD\uFFFDH\uFFFD\u001Dc\uFFFD.\uFFFD\uFFFD\uFFFDiZ\uFFFD\n\uFFFD>\uFFFD\uFFFD\u00078\u0014]\uFFFDc/\uFFFDL9\uFFFD
phone=
role=ADMIN
theme=dark
